DEFAULT_LOCATION = {
    "country": "Uzbekistan",
    "region": "Bukhara Region",
    "city": "Bukhara",
}

ROLE_PERMISSIONS = {
    "superadmin": {
        "place:create",
        "place:update",
        "place:delete",
        "place:view",
        "review:create",
        "review:update",
        "review:delete",
        "review:view",
        "favorite:create",
        "favorite:delete",
        "favorite:view",
        "profile:view",
        "profile:update_location",
    },
    "manager": {
        "place:create",
        "place:update",
        "place:view",
        "review:create",
        "review:update",
        "review:delete",
        "review:view",
        "favorite:create",
        "favorite:delete",
        "favorite:view",
        "profile:view",
        "profile:update_location",
    },
    "user": {
        "place:view",
        "review:create",
        "review:update",
        "review:delete",
        "review:view",
        "favorite:create",
        "favorite:delete",
        "favorite:view",
        "profile:view",
        "profile:update_location",
    },
}
