# Generated by Django 5.2.12 on 2026-04-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='region',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('manager', 'Manager'), ('user', 'User')], db_index=True, default='user', max_length=32),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
